# render.yaml - VERSIÓN MEJORADA
services:
  - type: web
    name: diplomas-proyecto
    env: python
    plan: free
    region: oregon

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: uvicorn api_verificacion:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      
      # ✅ MEJOR: Usar variable generada en lugar de hardcodeada
      - key: ADMIN_TOKEN
        generateValue: true
      
      - key: SALIDA_PDFS
        value: out

      # Base de datos Clever Cloud
      - key: DB_HOST
        fromGroup: clever-cloud-db
      - key: DB_NAME
        fromGroup: clever-cloud-db
      - key: DB_USER
        fromGroup: clever-cloud-db
      - key: DB_PASSWORD
        fromGroup: clever-cloud-db
      - key: DB_PORT
        value: 3306

      # Supabase
      - key: SUPABASE_URL
        fromGroup: supabase-config
      - key: SUPABASE_SERVICE_KEY
        fromGroup: supabase-config
      - key: SUPABASE_BUCKET
        value: diplomas
      - key: SUPABASE_PUBLIC_BASE
        fromGroup: supabase-config

      # ✅ IMPORTANTE: Actualizar esta URL
      - key: BASE_URL_VERIFICACION
        value: https://diplomas-proyecto.onrender.com

    healthCheckPath: /healthz
    autoDeploy: true

envVarGroups:
  - name: clever-cloud-db
    description: Credenciales de Clever Cloud MySQL
  - name: supabase-config
    description: Configuración de Supabase Storage