# =======================================================
# render.yaml — configuración para Render.com
# Proyecto: Portal Escolar · Diplomas
# =======================================================

services:
  - type: web
    name: diplomas-proyecto
    env: python
    plan: free
    region: oregon

    # --- Comando para construir dependencias ---
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    # --- Comando para ejecutar la app ---
    startCommand: uvicorn api_verificacion:app --host 0.0.0.0 --port $PORT

    # --- Variables de entorno ---
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      
      # Token de administrador
      - key: ADMIN_TOKEN
        value: GvfNb4GVZol2WcO5JBCR-aAJggi0dqXovif4pOQZH8
      
      # Carpeta de salida de PDFs
      - key: SALIDA_PDFS
        value: out

      # === Configuración de base de datos Clever Cloud ===
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: 3306

      # === Configuración de Supabase (opcional, para sincronización de PDFs) ===
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: diplomas
      - key: SUPABASE_PUBLIC_BASE
        sync: false

      # === URL base para verificación ===
      - key: BASE_URL_VERIFICACION
        sync: false

    # --- Health check ---
    healthCheckPath: /healthz
    autoDeploy: true