# =======================================================
# render.yaml — configuración para Render.com
# Proyecto: Portal Escolar · Diplomas
# =======================================================

services:
  - type: web
    name: diplomas-proyecto
    env: python
    plan: free
    region: oregon

    # --- Comando para construir dependencias ---
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    # --- Comando para ejecutar la app ---
    startCommand: uvicorn api_verificacion:app --host 0.0.0.0 --port $PORT

    # --- Variables de entorno ---
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ADMIN_TOKEN
        value: GvfNb4GVZol2WcO5JBCR-aAJggi0dqXovif4pOQZH8
      - key: SALIDA_PDFS
        value: out

      # === Configuración de base de datos Clever Cloud ===
      - key: MYSQL_ADDON_HOST
        sync: false
      - key: MYSQL_ADDON_DB
        sync: false
      - key: MYSQL_ADDON_USER
        sync: false
      - key: MYSQL_ADDON_PASSWORD
        sync: false
      - key: MYSQL_ADDON_PORT
        value: 3306

    # --- Opcional: health check ---
    healthCheckPath: /healthz
    autoDeploy: true
